name: Deploy Héméa Privacy Policy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to docs branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
          clean: true
          single-commit: true